### ISSUE TITLE
Config files - add frames per second per channel

### ISSUE THREAD

**Issue by vstadnytskyi-FDA** [vstadnytskyi/intel-realsense-devices#27]
Depending on Intel realsense depth camera we can pick difference FPS for different channels. I propose we redesign configuration file and make it nested. In addition, to standard fields, I propose to have: FPS, buffer length, 

Here is an example of a section of config file:

```
channels:

  - #<-this is first entry in the channels list
    type: depth
    fps: 30
    buffer_length: 30

  - #<-this is second entry in the channels list
    type: color
    fps: 30
    buffer_length: 30
```
     
Let us discuss. 

I propose we split each stream(channel) in a different entry in the configuration file and assign different circular buffers and different FPS to each channel. It will provide more flexibility in future development. Though, it would add a little bit more coding. 

What do you think?
